config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  scope module: 'home' do
    get 'oauths/oauth'
    get 'oauths/callback'
    resources :sessions, only: [:new, :create]
    resources :registrations, only: [:new, :create]
    root to: 'registrations#index'
    get 'login', to: 'sessions#new', :as => :login
    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider', to: 'oauths#oauth', :as => :auth_at_provider
  end

  scope module: 'dashboard' do
    resources :sessions, only: [:destroy]
    resource :user, only: [:edit, :update, :show]
    post 'trainers/:id/review', to: 'trainers#review', as: 'trainer'
    resources :cards
    resources :decks
    delete 'logout', to: 'sessions#destroy'
  end

  scope '(:locale)', locale: /en|ru/ do
    resources :login
    resources :registrations
  end

end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user
  belongs_to :deck

  validates :original_text, presence: true
  validates :translated_text, presence: true
  validates :review_date, presence: true
  validates :original_text, uniqueness: true
  validate :check_uniqueness
  before_validation :is_automatically_set

  mount_uploader :avatar, AvatarUploader

  def is_automatically_set
    # self.review_date ||= 3.days.from_now
    self.review_date ||= Time.now
  end

  def check_uniqueness
    unless self.original_text.downcase != self.translated_text.downcase
      errors.add(:base, I18n.t('uniqueness'))
    end
  end

  def self.get_random
    Card.where('review_date <= ?', Time.current).order('RANDOM()').first
  end

  def self.send_notification
    users = User.joins(:cards).where('cards.review_date <= ?', Time.current)
    users.each do |user|
      CardsMailer.pending_cards_notification(user).deliver_now
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = current_user.cards
    @card = current_user.cards.get_random
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @card.to_json }
    end
  end

  def show
    unless @card
      render text: 'Page not found', status: 404
    end
  end

  def new
    @card = current_user.cards.new
  end

  def edit;
  end

  def create
    @card = current_user.cards.create(card_params)
    if @card.valid?
      redirect_to card_path(@card), notice: 'card is created!'
    else
      render 'new'
    end
  end

  def update
    @card.update_attributes(card_params)
    if @card.valid?
      redirect_to card_path(@card)
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_url
  end

  private

  def find_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :avatar, :deck_id)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = current_user.cards
    @card = current_user.cards.get_random
  end

  def show
    unless @card
      render text: 'Page not found', status: 404
    end
  end

  def new
    @card = current_user.cards.new
  end

  def edit; end

  def create
    @card = current_user.cards.create(card_params)
    if @card.valid?
      redirect_to card_path(@card), notice: 'card is created!'
    else
      render 'new'
    end
  end

  def update
    @card.update_attributes(card_params)
    if @card.valid?
      redirect_to card_path(@card)
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_url
  end

  private

  def find_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :avatar, :deck_id)
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = current_user.decks.all
  end

  # GET /decks/1
  # GET /decks/1.json
  # def show
  #   unless @deck
  #     render text: 'deck not found', status: 404
  #   end
  # end

  # GET /decks/new
  def new
    @deck = current_user.decks.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = current_user.decks.create(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = current_user.decks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end

end

app/controllers/dashboard/trainers_controller.rb
require 'damerau-levenshtein'
class Dashboard::TrainersController < ApplicationController
  skip_before_action :require_login

    def review
      result = CheckCard.call(params: card_params, user: current_user)
      redirect_to :back, notice: result.notice
    end

  def card_params
    params.permit(:original_text, :id)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @user = current_user
  end

  # GET /users/1/edit
  def edit; end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if current_user.update(user_params)
      redirect_to user_path,
                  notice: 'User was successfully updated'
    else
      redirect_to edit_user_path
    end
  end

  private

  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password_confirmation, :password, :current_deck_id, :language)
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  # def time_format(d)
  #   current_time = Time.now.strftime('%m/%d/%Y')
  #   d.gsub!(/[0-9a-zA-Z]/, current_time)
  # end

end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
<%= f.input :original_text %>
<%= f.input :translated_text %>
<%= f.file_field :avatar %>
<%= f.hidden_field :avatar_cache %>
<%= f.input :deck_id, collection: current_user.decks%>
<%= f.button :submit %>
<% end %>

app/views/dashboard/cards/edit.html.erb
<h1>Edit card</h1>
    <%= render partial: 'form', locals: { submit: t(:save) } %>

app/views/dashboard/cards/index.html.erb
<% if @cards.empty? %>
    <b>no items in store</b>
<% else %>
    <table>
      <tr>
        <th><%=t(:image) %></th>
        <th><%=t(:original_text) %></th>
        <th><%=t(:translated_text) %></th>
        <th><%=t(:review_date) %></th>
      </tr>

      <% @cards.each do |card| %>
          <tr>
            <td><%= image_tag(card.avatar_url(:thumb)) if card.avatar? %></td>
            <td><%= card.original_text %></td>
            <td><%= card.translated_text %></td>
            <td><%= card.review_date %></td>
            <td><%= link_to t(:edit), edit_card_path(card) %></td>
            <td><%= button_to t(:delete), card_path(card), method: :delete, data: { confirm: t(:confirm) } %></td>
          </tr>
      <% end %>

<% end %>

<h1><%= t(:translate_card) %></h1>
<% if @card.blank? %>
    <b><%= t(:no_items) %></b>
<% else %>
    <p>
       <%= t(:eng_translation) %> <%= @card.translated_text %>
    </p>

    <p>
      <%= form_tag trainer_path(@card) do %>
          <%= image_tag(@card.avatar_url(:thumb)) if @card.avatar? %>
           <%= t(:your_translation) %> <%= text_field_tag :original_text %>
          <%= submit_tag t(:check_translation) %>
      <% end %>
<% end %>

</p>

app/views/dashboard/cards/new.html.erb
<%= render partial: 'form', locals: { submit: 'create' } %>
<%= link_to t(:back), decks_path %>

app/views/dashboard/cards/show.html.erb
<ul>
  <li><%= @card.original_text%></li>
  <li><%= @card.translated_text%></li>
  <li><%= @card.review_date%></li>
</ul>