config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  scope module: 'home' do
    get 'oauths/oauth'
    get 'oauths/callback'
    resources :sessions, only: [:new, :create]
    resources :registrations, only: [:new, :create]
    root to: 'registrations#index'
    get 'login', to: 'sessions#new', :as => :login
    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider', to: 'oauths#oauth', :as => :auth_at_provider
  end

  scope module: 'dashboard' do
    resources :sessions, only: [:destroy]
    resource :user, only: [:edit, :update, :show]
    post 'trainers/:id/review', to: 'trainers#review', as: 'trainer'
    resources :cards
    resources :decks
    delete 'logout', to: 'sessions#destroy'
  end

  scope '(:locale)', locale: /en|ru/ do
    resources :login
    resources :registrations
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title><%= t(:title) %></title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>
<section id='container'>
  <h1><p><%= t(:title) %></p></h1>
  <ul class='navigation-links'>
    <% unless params[:controller] == 'cards' && params[:action] == 'index' %>
        <%= link_to 'All cards', cards_path %>
    <% end %>
    <%= link_to t(:add_deck), decks_path %>
    <%= link_to t(:add_card), new_card_path %>
    <%= link_to t(:profile), edit_user_path %>

  </ul>
  <p><%= t(:paragraph) %></p>

  <div id='nav'>
    <% if current_user %>

        <%= link_to t(:logout), :logout, method: :delete %>
    <% else %>
        <%= link_to t(:register), new_registration_path %> |
        <%= link_to t(:login), :login %>
        <% I18n.available_locales.each do |locale| %>
            <%= link_to locale, root_path(locale: locale),
                        class: 'navbar-link' %>
        <% end %>
    <% end %>
  </div>
  <div>
    <p id='notice'><%= flash[:notice] %></p>

    <p id='alert'><%= flash[:alert] %></p>
  </div>
  <%= yield %>
</section>
<% if flash[:message] %>
    <div class='notice'><%= flash[:notice] %></div>
<% end %>

<div><%= link_to 'Login with Twitter', auth_at_provider_path(:provider => :twitter) %></div>
<div><%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %></div>
</body>
</html>